version: '3.8'

services:
  monitor-service:
    container_name: monitor-service
    build: .
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Sao_Paulo
